version: '3.8'

services:
  itmo_bot_service:
    build: .
    container_name: itmo_bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped